### ISSUE TITLE
support using multiple Isolates

### ISSUE THREAD

**Issue by tbsaunde** [mozilla/spidernode#100]
We have a couple TODO comments about this.  Off hand I'm not sure if the right way to do this is 1:1 Isolate to JSContext, N;1 or something else.

**Comment by tbsaunde** [comment]
in terms of the Isolate classes themselves this should be easy, we should be able to copy what v8 does which is to have the tls slot point to a stack of Isolate*

**Comment by brendandahl** [comment]
From what I've seen it looks like node only uses one isolate, so I'm not sure this is really needed (chakra also does not support this).

**Comment by tbsaunde** [comment]
On Tue, May 17, 2016 at 12:03:21PM -0700, Brendan Dahl wrote:

> From what I've seen it looks like node only uses one isolate, so I'm not sure
> this is really needed (chakra also does not support this).

yes, I believe node only uses one with the possible exception of the
debug stuff, I haven't dug into that much.  However we have some TODO
comments about it, and while we don't need to do it for Node we might as
well log it on the list of stuff to support the v8 API.

**Comment by mykmelez** [comment]
> yes, I believe node only uses one with the possible exception of the debug stuff, I haven't dug into that much. However we have some TODO comments about it, and while we don't need to do it for Node we might as well log it on the list of stuff to support the v8 API.

Indeed. It'd just be useful to distinguish the parts of the V8 API we need for Node from the rest of the V8 API. We already have a `v8-api` label we've been using for the Node bits. I've created the `v8-api-all` label for the rest of them.

**Comment by ehsan** [comment]
ab9c290 should be the last part of this.  Now we should support using multiple isolates just fine.
