### ISSUE TITLE
`make clean` doesn't clean up everything

### ISSUE THREAD

**Issue by brendandahl** [mozilla/spidernode#109]
I noticed when I changed build-spidermonkey.sh and did a `make clean`, `configure` and `make` things didn't get updated. I had to manually go wipe out Release/Debug dirs.

**Comment by ehsan** [comment]
I think you want [distclean](https://github.com/mozilla/spidernode/blob/91630a6e5b1b9ee1451d7441b7572a86ae8e5862/Makefile#L96).

**Comment by ehsan** [comment]
(Please reopen if I'm missing something.)
