### ISSUE TITLE
Implement FunctionTemplate::HasInstance

### ISSUE THREAD

**Issue by bzbarsky** [mozilla/spidernode#143]
Need to figure out what it should actually do.

**Comment by ehsan** [comment]
[`FunctionTemplateInfo::IsTemplateFor`](https://github.com/mozilla/spidernode/blob/65ce83e5ea0eedfa9a6927af80c64bee9170dcbf/deps/v8/src/objects.cc#L930) is the core of the logic, I think.

It obtains the object's constructor, and looks through the `FunctionTemplateInfo` template chain for that function, if one exists, and returns true if something in that chain is equal to `this`.

**Comment by bzbarsky** [comment]
See https://github.com/mozilla/spidernode/issues/152
