### ISSUE TITLE
Figure out what to do with Signature in FunctionTemplate stuff

### ISSUE THREAD

**Issue by bzbarsky** [mozilla/spidernode#144]
It's supposed to enforce some constraint on ... well what?  Sounds kind of like on the holder, which is a fairly useless thing in practice.

Anyway, looking at chakrashim, they set the "holder" for their calls to the "this" value unless there is a Signature.  If there is, they call Utils::CheckSignature, which always sets "holder" to "this", but ensure that the object involved is an instance of the instance template of the function template that was originally passed to Signature::New (which only accepts conditions on "this", not on args, in chakrashim).  They do this by storing the object template used to construct each object in that object, and just checking that the stored thing is the instance template involved.

We could do something similar: store the Signature (aka FunctionTemplate) in our JSFunction, then if there is one get its instance template's JSClass and compare to it.  This would require us to always use a custom JSClass for instances, of course.

**Comment by ehsan** [comment]
> Anyway, looking at chakrashim, they set the "holder" for their calls to the "this" value unless there is a Signature. If there is, they call Utils::CheckSignature, which always sets "holder" to "this", but ensure that the object involved is an instance of the instance template of the function template that was originally passed to Signature::New (which only accepts conditions on "this", not on args, in chakrashim). They do this by storing the object template used to construct each object in that object, and just checking that the stored thing is the instance template involved.

Yes, this is how signatures work.

> We could do something similar: store the Signature (aka FunctionTemplate) in our JSFunction, then if there is one get its instance template's JSClass and compare to it. This would require us to always use a custom JSClass for instances, of course.

I think we can implement this more simply, by using `FunctionTemplate::HasInstance` that I'm implementing in #143.  That way, the signature check would be something along the lines of `signature->HasInstance(thisVal)`.

I'll take a stab at this.

**Comment by bzbarsky** [comment]
> I think we can implement this more simply, by using FunctionTemplate::HasInstance that I'm implementing in #143

As I noted in https://github.com/mozilla/spidernode/issues/152 it's not clear to me whether `HasInstance` has the right semantics there.  It depends on what "get the constructor" means in `HasInstance`.
