### ISSUE TITLE
Remove the workaround for |for (const of iterable)|

### ISSUE THREAD

**Issue by ehsan** [mozilla/spidernode#151]
ac098cd6436799c58c263f4346ab85aca39282ef works around [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1278150).  We should remove it once that's fixed in SpiderMonkey.

**Comment by ehsan** [comment]
2d4924e added some more workarounds.

**Comment by tbsaunde** [comment]
e892014

**Comment by ehsan** [comment]
Another one: 47b1ee56435800a8cf3636924f2276f583ba69f4

**Comment by evilpie** [comment]
If you updated SpiderMonkey this should work now.

**Comment by ehsan** [comment]
Thanks, I have reverted all of these workarounds.
