### ISSUE TITLE
Builds got way slower as a result of a9e04fe97b390d96172ff0de5669f3fbea6eb784

### ISSUE THREAD

**Issue by bzbarsky** [mozilla/spidernode#155]
Some data (opt build, because for a bit there we had a typoed assert in the tree, sorry):

Building from 8573705f50e555d48e39bd240a0452431c619f10 (no-op build after finishing previous build):
    spidernode% time make
    ....
    7.732u 0.638s 0:07.10 117.7%    0+0k 0+32io 0pf+0w

Building from a9e04fe97b390d96172ff0de5669f3fbea6eb784 (no-op build after finishing previous build):
    spidernode% time make
    ....
    8.059u 0.697s 1:05.57 13.3%     0+0k 0+15io 0pf+0w

The build spends a lot of time just sitting there after the last line of `make` output.... Looks like a 60s sleep or something.

**Comment by ehsan** [comment]
Sorry for breaking this!
