### ISSUE TITLE
Figure out what should happen when constructing with a native callback that returns a primitive

### ISSUE THREAD

**Issue by bzbarsky** [mozilla/spidernode#157]
The IsConstructorCall test has a part (commented out) where it does `new f()` where `f` is a function created from a `FunctionTemplate` which always returns a boolean (in particular, whether it was called as `f()` or `new f()`.

This fails because in SpiderMonkey `CallJSNativeConstructor` asserts that the return value of JSNative constructor is an object.  Which it really should be, in any sane case...

**Comment by ehsan** [comment]
c478dfd67f0a08e856043975b72c345b170aa350 made sure that we follow the ES6 semantics there (which is, to box primitives.)  The test can now be uncommented.
