### ISSUE TITLE
SpiderNode assumes libstdc++ on Mac; fails on "'tr1/type_traits' file not found" with libc++

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#166]
SpiderNode assumes libstdc++ on Mac, where it includes the <tr1/type_traits> header, which is only available in libstdc++:

https://github.com/mozilla/spidernode/blob/f9cd4f69439cda19997f191adcd679a17c1d18fd/src/util.h#L13-L17

But Electron builds with libc++:

https://github.com/electron/electron/blob/master/toolchain.gypi#L115-L116

So when I configure Electron to build SpiderNode, the build fails with "'tr1/type_traits' file not found."

**Comment by ehsan** [comment]
I have a fix for this which I'll push to master shortly, but note that per https://github.com/nodejs/node-gyp/issues/469, you shouldn't be changing the gyp flags to build with libc++, just target OSX 10.9, by setting:

```
export CXXFLAGS="-mmacosx-version-min=10.9"
export LDFLAGS="-mmacosx-version-min=10.9"
```

before configuring.

I will also upstream this fix to node.

**Comment by ehsan** [comment]
Upstream fix: https://github.com/nodejs/node/pull/7778
