### ISSUE TITLE
implement Error.captureStackTrace()

### ISSUE THREAD

**Issue by tbsaunde** [mozilla/spidernode#168]
a bunch of tests fail because we don't define a captureStackTrace function on the Error global.  v8 seems to implement this with some special builtin js.  I'm not sure exactly what it does yet, but I think it roughly does what you'd expect and create a stack trace object.

**Comment by ehsan** [comment]
This is documented [here](https://github.com/mozilla/spidernode/blob/master/doc/api/errors.md#errorcapturestacktracetargetobject-constructoropt).

Since SpiderMonkey already implements `Error.stack`, we should be able to just stub that function out.
