### ISSUE TITLE
Configurable spidermonkey linking

### ISSUE THREAD

**Issue by brendandahl** [mozilla/spidernode#178]
In positron we'll need to link spidernode against the spidermonkey built in positron.

**Comment by mykmelez** [comment]
@ehsan Do I understand correctly that this requires you to build both debug and release SpiderMonkey to build SpiderNode?

**Comment by mykmelez** [comment]
> @ehsan Do I understand correctly that this requires you to build both debug and release SpiderMonkey to build SpiderNode?

Ah, no, I see from the code that you can build release only.
