### ISSUE TITLE
build issue on Ubuntu 14.04

### ISSUE THREAD

**Issue by LarkspurRaven** [mozilla/spidernode#184]
I am trying to build spidernode on Ubuntu Linux version 14.04. I am seeing these failures after configuring spidernode and running make. I'm following the instructions in the README and I've separately built a standard version of node, so I know all the node dependencies are met. Any suggestions on what to do?

~/spidernode$ git clone https://github.com/mozilla/spidernode.git
~/spidernode$ cd spidernode
~/spidernode/spidernode$ ./configure
...
~/spidernode/spidernode$ make
make -C out BUILDTYPE=Release V=1
make[1]: Entering directory `/home/spidernode/spidernode/out'
  touch _home_spidernode_spidernode_deps_spidershim_spidermonkey_gyp_spidermonkey_target_build_spidermonkey.intermediate
  LD_LIBRARY_PATH=/home/spidernode/spidernode/out/Release/lib.host:/home/spidernode/spidernode/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps/spidershim; mkdir -p /home/spidernode/spidernode/out/Release/spidermonkey/js/src /home/spidernode/spidernode/out/Release/spidermonkey/mozglue/build; scripts/build-spidermonkey.sh "/home/spidernode/spidernode/out/Release/spidermonkey"
scripts/build-spidermonkey.sh: line 12: --version: command not found
scripts/build-spidermonkey.sh: line 12: test: too many arguments
make[2]: Entering directory '/home/spidernode/spidernode/out/Release/spidermonkey'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory`/home/spidernode/spidernode/out/Release/spidermonkey'
/home/spidernode/spidernode/out/Release/spidermonkey
**scripts/build-spidermonkey.sh: line 63: /home/spidernode/spidernode/deps/spidershim/spidermonkey/js/src/configure: No such file or directory**
make[1]: **\* [_home_spidernode_spidernode_deps_spidershim_spidermonkey_gyp_spidermonkey_target_build_spidermonkey.intermediate] Error 127
rm _home_spidernode_spidernode_deps_spidershim_spidermonkey_gyp_spidermonkey_target_build_spidermonkey.intermediate
make[1]: Leaving directory `/home/spidernode/spidernode/out'
make: **\* [node] Error 2

**Comment by rikelme** [comment]
+1

**Comment by brendandahl** [comment]
It's failing on https://github.com/mozilla/spidernode/blob/8f5b2460e0bf84adef9c4c52d5764d4fcea45efe/deps/spidershim/scripts/build-spidermonkey.sh#L12

What version of autoconf are you using?

**Comment by LarkspurRaven** [comment]
Hi Brendan,

I am using autoconf version # 2.69.

**Comment by tbsaunde** [comment]
On Thu, Aug 11, 2016 at 02:26:33PM -0700, henbagan wrote:

> Hi Brendan,
> 
> I am using autoconf version # 2.69.

you need to use 2.13.

Trev

**Comment by ehsan** [comment]
Yeah, the current master should issue a more descriptive error message about this.
