### ISSUE TITLE
Compartment mismatch with setTimeout in shell

### ISSUE THREAD

**Issue by brendandahl** [mozilla/spidernode#187]
Using spidernode shell:

Try

```
> setTimeout(function() {});
```

**\* Compartment mismatch 0x106b85800 vs. 0x104829000
Hit MOZ_CRASH() at /Users/bdahl/projects/spidernode/deps/spidershim/spidermonkey/js/src/jscntxtinlines.h:40
^C^C^C^CSegmentation fault: 11

Works fine within a file.

**Comment by ehsan** [comment]
This seems to have been fixed on master.  Please reopen if you can reproduce.
