### ISSUE TITLE
Collaboration on spidernode wiki

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/spidernode#202]
As mentioned in https://github.com/mozilla/spidernode/pull/201#issuecomment-245978745 GitHub does not make it easy for non-contributors to collaborate on spidernode with respect to non-code elements.

However, it is possible to [relax the permissions for the wiki](https://help.github.com/articles/changing-access-permissions-for-wikis/) for the general public.

I opened a ticket so we can find a consensus whether it is worthwhile.

**Comment by ehsan** [comment]
You should now be able to edit the wiki!

**Comment by Ryuno-Ki** [comment]
Yay!

Added [the glossary](https://github.com/mozilla/spidernode/wiki/Glossary) as proof.
