### ISSUE TITLE
Can't set internal fields on global's prototype object

### ISSUE THREAD

**Issue by petervanderbeken** [mozilla/spidernode#204]
I'm trying to use some code that uses the v8 API, but trying to make it use Spidershim. This code fails: `v8Context->Global()->GetPrototype()->ToObject(v8Context).ToLocalChecked()->SetAlignedPointerInInternalField(0, ...);`, because it looks like the global object's prototype is a regular JS object without reserved slots.
I stumbled on this code in v8: https://github.com/v8/v8/blob/a717fb7c013bf96f8b037cecf2f8a50f9c879a85/src/api.cc#L6129 and it looks like we should do something similar. In v8 the global is just a proxy though, so I'm not sure if we need to align Spidershim more with that or just spot-fix this. I tried adding `global_template->GetConstructor()->SetPrototypeTemplate(global_template);` in Context::New, right before the call to CreateGlobal and that seems to work (FunctionTemplate::GetFunction uses the proto object template to create the prototype).

**Comment by ehsan** [comment]
I've been hoping to get away without replicating the proxy setup...  I think spot fixing this is fine.  I'll write a patch tomorrow.
