### ISSUE TITLE
run-tests.py throws "maximum recursion depth exceeded while calling a Python object"

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#207]
On my Linux (Ubuntu 14.04 LTS) VM, invoking run-tests.py throws "maximum recursion depth exceeded while calling a Python object":

```
$ ./deps/spidershim/scripts/run-tests.py
Exception:  maximum recursion depth exceeded while calling a Python object

Note: an error occurred while running gyp using multiprocessing.
For more verbose output, set GYP_PARALLEL=0 in your environment.
If the error only occurs when GYP_PARALLEL=1, please report a bug!
```

Unfortunately, setting `GYP_PARALLEL=0` doesn't produce the promised "more verbose output":

```
$ GYP_PARALLEL=0 ./deps/spidershim/scripts/run-tests.py
Exception:  maximum recursion depth exceeded while calling a Python object

Note: an error occurred while running gyp using multiprocessing.
For more verbose output, set GYP_PARALLEL=0 in your environment.
If the error only occurs when GYP_PARALLEL=1, please report a bug!
```

**Comment by tbsaunde** [comment]
On Wed, Oct 05, 2016 at 02:51:44PM -0700, Myk Melez wrote:

> On my Linux (Ubuntu 14.04 LTS) VM, invoking run-tests.py throws "maximum
> recursion depth exceeded while calling a Python object":
> 
> $ ./deps/spidershim/scripts/run-tests.py
> Exception:  maximum recursion depth exceeded while calling a Python object
> 
> Note: an error occurred while running gyp using multiprocessing.
> For more verbose output, set GYP_PARALLEL=0 in your environment.
> If the error only occurs when GYP_PARALLEL=1, please report a bug!

I'm not sure why, but the script works for me.

> Unfortunately, setting GYP_PARALLEL=0 doesn't produce the promised "more
> verbose output":
> 
> $ GYP_PARALLEL=0 ./deps/spidershim/scripts/run-tests.py
> Exception:  maximum recursion depth exceeded while calling a Python object
> 
> Note: an error occurred while running gyp using multiprocessing.
> For more verbose output, set GYP_PARALLEL=0 in your environment.
> If the error only occurs when GYP_PARALLEL=1, please report a bug!

I wonder if this is the same parallel as the params one in
run-tests.py:55, maybe try changing that to false?

That get_targets function feels kind of funky, and I'd be tempted to
make it just parse the gyp file itself, but contrary to what I thought
its not actually valid json because it uses ' instead of ".  Or maybe it
would be better to generate the gyp file, but I'm not sure how to do
that.

**Comment by ehsan** [comment]
I think we should just set GYP_PARALLEL to 0 in get_targets.  Trying to do parallel gyp processing in run-tests.py is a waste of time!

**Comment by mykmelez** [comment]
@tbsaunde landed a change to make run-tests.py run gyp single-threaded by default, and I still see the error, but now I get a stack trace:

```
$ ./deps/spidershim/scripts/run-tests.py
Traceback (most recent call last):
  File "./deps/spidershim/scripts/run-tests.py", line 105, in <module>
    sys.exit(main())
  File "./deps/spidershim/scripts/run-tests.py", line 14, in main
    targets, external_sm = get_targets(base_dir)
  File "./deps/spidershim/scripts/run-tests.py", line 73, in get_targets
    default_variables=default_variables)
  File "/usr/lib/python2.7/dist-packages/gyp/__init__.py", line 131, in Load
    params['parallel'])
  File "/usr/lib/python2.7/dist-packages/gyp/input.py", line 2639, in Load
    variables, includes, depth, check, True)
  File "/usr/lib/python2.7/dist-packages/gyp/input.py", line 388, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "/usr/lib/python2.7/dist-packages/gyp/input.py", line 1141, in ProcessVariablesAndConditionsInDict
    variables, build_file, 'variables')
  File "/usr/lib/python2.7/dist-packages/gyp/input.py", line 1193, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "/usr/lib/python2.7/dist-packages/gyp/input.py", line 1070, in ProcessConditionsInDict
    variables, build_file)
  File "/usr/lib/python2.7/dist-packages/gyp/input.py", line 1148, in ProcessVariablesAndConditionsInDict
    expanded = ExpandVariables(value, phase, variables, build_file)
  File "/usr/lib/python2.7/dist-packages/gyp/input.py", line 976, in ExpandVariables
    output = ExpandVariables(output, phase, variables, build_file)
  …
  [987 more occurrences of …/gyp/input.py line 976, in ExpandVariables]
  …
  File "/usr/lib/python2.7/dist-packages/gyp/input.py", line 711, in ExpandVariables
    matches = list(variable_re.finditer(input_str))
RuntimeError: maximum recursion depth exceeded while calling a Python object while trying to load deps/spidershim/tests.gyp
```

**Comment by tbsaunde** [comment]
On Thu, Oct 13, 2016 at 03:54:05PM -0700, Myk Melez wrote:

> @tbsaunde landed a change to make run-tests.py run gyp single-threaded by
> default, and I still see the error, but now I get a stack trace:
> 
> $ ./deps/spidershim/scripts/run-tests.py
> Traceback (most recent call last):
>   File "./deps/spidershim/scripts/run-tests.py", line 105, in <module>
>     sys.exit(main())
>   File "./deps/spidershim/scripts/run-tests.py", line 14, in main
>     targets, external_sm = get_targets(base_dir)
>   File "./deps/spidershim/scripts/run-tests.py", line 73, in get_targets
>     default_variables=default_variables)
>   File "/usr/lib/python2.7/dist-packages/gyp/**init**.py", line 131, in Load
>     params['parallel'])

ah! so you have a distro provided gyp that is getting prefered to the one
in the node tree.  I'm curious why that's a problem, but perhaps the
easiest fix is to just prepend the path to the node one to sys.path
instead of appending it.

**Comment by mykmelez** [comment]
> ah! so you have a distro provided gyp that is getting prefered to the one in the node tree. I'm curious why that's a problem, but perhaps the easiest fix is to just prepend the path to the node one to sys.path instead of appending it.

My distro is old (Ubuntu 14.04 LTS), so its GYP is presumably similarly old. Unfortunately, GYP isn't versioned, so I can't compare the two installs by version. But that's an indication of the more general issue that GYP wasn't designed to be used by third-parties, so it presumably doesn't prioritize backward-compatibility, which results in bugs like this one.

I'm not sure why I even need distro GYP, but distro NPM apparently depends on it. Go figure. In any case, #209 fixes the issue by prepending local GYP to sys.path, as you suggested.
