### ISSUE TITLE
Mac jobs on Travis occasionally time out on "travis_wait 60 make …"

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#210]
Mac jobs on Travis occasionally time out on `$ travis_wait 60 make V= $MAKE_ARGS -C out BUILDTYPE=$(if [ "$ENABLE_DEBUG" == "true" ]; then echo 'Debug'; else echo 'Release'; fi)` because no output is received for some overlong period of time. So far every time I've retriggered such a job, it has succeeded the second time around.

One example is [Job #515.17](https://travis-ci.org/mozilla/spidernode/jobs/168946323). Unfortunately, I retriggered that job without saving the log from the run that timed out, and Travis doesn't seem to make the old log available. I'll save one next time around and post it here.

**Comment by Ryuno-Ki** [comment]
At work, I experienced timeouts in Jenkins, because a CLI opened an interactive shell (or TUI, if you like. It looks like `less` or `more` output). Locally it didn't behaved like that. The OS and versioned differed, though …

Can you exclude that this happened here?

**Comment by mykmelez** [comment]
> At work, I experienced timeouts in Jenkins, because a CLI opened an interactive shell (or TUI, if you like. It looks like less or more output). Locally it didn't behaved like that. The OS and versioned differed, though …

The _travis_wait_ indirection should give the _make_ invocation 60 minutes to return a result, so either _make_ is really taking longer than that to build the project on occasion, or it stalls at some point. The latter is more likely, since builds that succeed take no more than ~43 minutes.

**Comment by mykmelez** [comment]
After observing some cases in which a job failed because `The job exceeded the maximum time limit for jobs, and has been terminated.`, such as https://travis-ci.org/mykmelez/spidernode/jobs/194547495, I remembered that Travis has a 50 minute time limit for Mac jobs.

I don't recall the exact failure that prompted me to file this issue, but it may have been caused by a job running too long, so I've optimistically marked #354, which attempts to reduce build times, as resolving this issue.
