### ISSUE TITLE
test-cluster-master-kill asserts: null === 0

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#241]
>=== release test-cluster-master-kill ===                    
>Path: parallel/test-cluster-master-kill
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>
>:0
>
>
>AssertionError: null === 0
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cluster-master-kill.js
>--- CRASHED (Signal: 11) ---

**Comment by tbsaunde** [comment]
On Wed, Dec 14, 2016 at 02:25:55PM -0800, Myk Melez wrote:
>     === release test-cluster-master-kill ===
>     Path: parallel/test-cluster-master-kill
>     Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/
>     spidershim/spidermonkey/js/src/threading/Thread.h:122
>     Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/
>     spidershim/spidermonkey/js/src/threading/Thread.h:122
> 
>     :0
> 
>     AssertionError: null === 0
>     Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/
>     spidershim/spidermonkey/js/src/threading/Thread.h:122
>     Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/
>     test-cluster-master-kill.js
>     --- CRASHED (Signal: 11) ---

other than the joinable business which seems to generally show up for
you  but not for me here's what I see with this test.

bit length overflow
code 18 bits 7->6
code 6 bits 5->6

bit length overflow
code 18 bits 7->6
code 6 bits 5->6

bit length overflow
code 18 bits 7->6
code 6 bits 5->6

bit length overflow
code 18 bits 7->6
code 6 bits 5->6

bit length overflow
code 18 bits 7->6
code 6 bits 5->6

bit length overflow
code 18 bits 7->6
code 6 bits 5->6

Which seems like it might be fine.

Trev

**Comment by mykmelez** [comment]
> bit length overflow code 18 bits 7->6 code 6 bits 5->6

These messages started appearing after a merge from upstream Node last month. They come from deps/zlib/trees.c (lines 530 to 564). I filed #363 on them.

**Comment by mykmelez** [comment]
Now works for me.
