### ISSUE TITLE
test-repl-underscore throws: TypeError: invalid arguments

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#277]
>=== release test-repl-underscore ===                            
>Path: parallel/test-repl-underscore
>JS error at <no filename>:0: uncaught exception: AssertionError: [ '10', '10', 'Clearing context...', '10', '20', '20' ] deepStrictEqual [ 'Expression assignment to _ now disabled.',
>  '10',
>  '10',
>  'Clearing context...',
>  '10',
>  '20',
>  '20' ]
>
>:0
>
>
>AssertionError: [ '10', '10', 'Clearing context...', '10', '20', '20' ] deepStrictEqual [ 'Expression assignment to _ now disabled.',
>  '10',
>  '10',
>  'Clearing context...',
>  '10',
>  '20',
>  '20' ]
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-repl-underscore.js
>--- CRASHED (Signal: 11) ---

**Comment by Ryuno-Ki** [comment]
What a long issue title...

**Comment by mykmelez** [comment]
test-repl-underscore now throws `TypeError: invalid arguments`:

>=== release test-repl-underscore ===                    
>Path: parallel/test-repl-underscore
>JS error at buffer.js:33: TypeError: invalid arguments
>buffer.js:33
>
>
>
>TypeError: invalid arguments
>    at FastBuffer (buffer.js:33:5)
>    at fromString (buffer.js:240:12)
>    at Buffer.from (buffer.js:136:12)
>    at decodeChunk (_stream_writable.js:298:13)
>    at writeOrBuffer (_stream_writable.js:308:20)
>    at Writable.prototype.write (_stream_writable.js:257:11)
>    at _writeToOutput (readline.js:271:5)
>    at Interface.prototype.prompt (readline.js:236:5)
>    at REPLServer.prototype.displayPrompt (repl.js:651:3)
>    at REPLServer (repl.js:536:3)
>    at exports.start (repl.js:553:14)
>    at initRepl (/Users/myk/Projects/spidernode/test/parallel/test-repl-underscore.js:165:10)
>    at testSloppyMode (/Users/myk/Projects/spidernode/test/parallel/test-repl-underscore.js:15:13)
>    at /Users/myk/Projects/spidernode/test/parallel/test-repl-underscore.js:8:1
>    at Module.prototype._compile (module.js:585:16)
>    at Module._extensions[".js"] (module.js:595:3)
>    at Module.prototype.load (module.js:503:3)
>    at tryModuleLoad (module.js:466:5)
>    at Module._load (module.js:458:3)
>    at Module.runMain (module.js:620:3)
>    at run (bootstrap_node.js:437:7)
>    at startup (bootstrap_node.js:147:9)
>    at bootstrap_node.js:552:3
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-repl-underscore.js

**Comment by mykmelez** [comment]
Which means this is now a duplicate of #223.
