### ISSUE TITLE
test-sync-io-option asserts: Error: Command failed: [/path/to]/spidernode/out/Release/node [/path/to]/spidernode/test/parallel/test-sync- == null

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#283]
>=== release test-sync-io-option ===                          
>Path: parallel/test-sync-io-option
>:0
>
>
>AssertionError: { Error: Command failed: /Users/myk/Projects/spidernode/out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-sync- == null
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-sync-io-option.js
>--- CRASHED (Signal: 11) ---

**Comment by Ryuno-Ki** [comment]
What a long issue title...

**Comment by mykmelez** [comment]
Now works for me.
