### ISSUE TITLE
Deno on top of SpiderMonkey

### ISSUE THREAD

**Issue by HannanAkbar** [mozilla/spidernode#398]
I opened an issue on Deno's repository [Decoupling Deno from V8 Engine](https://github.com/denoland/deno/issues/237). However, Ryan Dahl has no plan to support any other engine, but I'm sure it's not that difficult to run Deno on top of SpiderMonkey. Deno uses N-API for extension modules and wraps V8 with a C library, libdeno.

Should we give it a try?

**Comment by mykmelez** [comment]
I'm not as sure as you are that it's not that difficult to run Deno on top of SpiderMonkey. The two JS engines have quite different APIs that reflect different underlying implementations, and we've found that it's quite hard to completely port Node.js to SpiderMonkey.

It also isn't clear what the user benefit is. So I would do more research (both technical and user) before deciding to give it a try. In any case, the way to do so would be to embed SpiderMonkey using its embedding APIs, not via SpiderNode, so this wouldn't be an issue for the SpiderNode repo. Thus I'll close this one.

See the SpiderMonkey docs for information about embedding it: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey

**Comment by Ryuno-Ki** [comment]
What about Chakra then?

**Comment by mykmelez** [comment]
@Ryuno-Ki I'm not very familiar with Chakra. Perhaps you should ask the https://github.com/nodejs/node-chakracore developers.

**Comment by Ryuno-Ki** [comment]
I was asking @HannanAkbar whether he had considered using Chakra instead of SpiderNode. Sorry, should have been more detailed.
