### ISSUE TITLE
archive spidernode project

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#403]
Given that this project hasn't been modified since 2017 (except to add a Code of Conduct) and is clearly no longer being developed, we should archive it.

**Comment by Ryuno-Ki** [comment]
Too bad, but obviously the resources aren't available too push this forward. It kinda makes me sad, that V8 is the only backend for Node now.
(Assuming that ChakraNode was dropped also with the move from EdgeHTML to V8 last year)

**Comment by mykmelez** [comment]
> Too bad, but obviously the resources aren't available too push this forward. It kinda makes me sad, that V8 is the only backend for Node now.

Indeed, I too wish it had turned out differently; but that's the situation, for now, anyway.

I'm going to archive the project. I'll close this issue now because I won't be able to do so after I archive it. Afterward, it'll remain possible to clone the project, if someone wants to work on it independently. And we can also unarchive it at any point if someone steps up to restart development within Mozilla.
