### ISSUE TITLE
Implement v8::StackTrace

### ISSUE THREAD

**Issue by evilpie** [mozilla/spidernode#42]
I am trying to implement this with JS::CaptureCurrentStack.

**Comment by evilpie** [comment]
Actually I have no idea how to return a StackTrace/StackFrame. We probably have to implement that as some kind of new class?

**Comment by ehsan** [comment]
> Actually I have no idea how to return a StackTrace/StackFrame. We probably have to implement that as some kind of new class?

You can get a `StackTrace` from `StackTrace::CurrentStackTrace()`.  `StackTrace` can hand out `StackFrame`s to callers.

Note that similar to `Context`, `StackTrace` and `StackFrame` probably don't need to be rooted separately (assuming that you use use the `v8local.h` APIs to create the `String` objects inside `StackFrame`), so you should be able to add an empty overload of `HandleScope::AddToScope` for `StackTrace` and `StackFrame`, just like the one we have for `Context`.

Hope this helps answer your question!

**Comment by ehsan** [comment]
This was done in c10216e0868d636b1d4266682e56001c9035a4a4, 077fcda44338709600f1bbca1c9ace733a2fad85 and fedf9f95f2dd3c00e66eb9b011021a89e973eaa5.  I'll add tests soon too.
