### ISSUE TITLE
SpiderShim.Date fails locally on strncmp(*utf8, datePortion, sizeof(datePortion) - 1)

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#43]
On my Mac, the SpiderShim.Date test fails:

> [ RUN      ] SpiderShim.Date
> ../deps/spidershim/test/value.cc:756: Failure
> Value of: strncmp(*utf8, datePortion, sizeof(datePortion) - 1)
>  Actual: 3
> Expected: 0
> [  FAILED  ] SpiderShim.Date (227 ms)

That doesn't seem to happen on Travis, though, so it may be a local configuration issue rather than a bug in SpiderNode. I'm unsure how the environments differ.

**Comment by ehsan** [comment]
Hmm, this passed on my Mac...  :/

What's the string value of `*utf8` there?

**Comment by mykmelez** [comment]
> What's the string value of *utf8 there?

It's `Wed Oct 22 2008 23:51:29 GMT-0700 (PDT)`!

**Comment by ehsan** [comment]
Ah, I get `Thu Oct 23 2008 02:51:29 GMT-0400 (EDT)`.  Didn't take us long before timezones bit us.  :(

**Comment by ehsan** [comment]
Please test with the current master, and reopen the issue if the test still fails.  Thanks!

**Comment by mykmelez** [comment]
It passes now!
