### ISSUE TITLE
String::NewFromUtf8 encodes to Latin-1 code points

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#44]
String::NewFromUtf8 currently uses JS_NewStringCopyN and JS_NewStringCopyZ to encode its input data, but those functions interpret the data as Latin-1, not UTF-8, so it encodes the data as a sequence of Latin-1 code points instead of UTF-8 code points.

Per @ehsan in https://github.com/mozilla/spidernode/pull/40#discussion_r60796855, we should be able to use "something like JS::UTF8CharsToNewTwoByteCharsZ() from js/CharacterEncoding.h first, and then using JS_NewUCString. I think in that case we can just transfer the ownership of the buffer that JS::UTF8CharsToNewTwoByteCharsZ() to the JS engine, so we wouldn't need to copy the buffer twice."

**Comment by ehsan** [comment]
Note for future reference that 0689ecc123a8d11fc54e26ccc2f3cee60fb5f45b is the commit that removed the test, so a fix here would need to revert that commit.
