### ISSUE TITLE
Add a helper for converting a v8::Value to JS::Value

### ISSUE THREAD

**Issue by ehsan** [mozilla/spidernode#72]
Right now we have `reinterpret_cast`s that give you a `JS::Value` out of a `v8::Value`, it would be nice to replace them with a helper function defined in a private header (similar to `v8local.h` for example.)  It would also be nice to make the function either return a pointer or a reference in all cases no matter if you pass it a `v8::Value*` or a `v8::Value&` and the `const` variants etc.

**Comment by tbsaunde** [comment]
pushed 4a2012b which I think fixes all the casts outside of rootstore and conversion.h
