### ISSUE TITLE
implement the other Isolate::RemovePersistent overloads

### ISSUE THREAD

**Issue by tbsaunde** [mozilla/spidernode#79]
looks trivial_Thanks for wanting to report an issue you've found in SpiderNode. Please delete
this text and fill in the template below. If unsure about something, just do as
best as you're able._

_Note that this is a work in progress, so most issues will be about the ongoing
development for now._

**Comment by tbsaunde** [comment]
actually this depends on stuff, leaving for now.

**Comment by ehsan** [comment]
The Template overloads done in 06604fa3d26f3a00dc2d00dcdb7e5f28ada8c13f.

**Comment by ehsan** [comment]
Most of these should be done now.
