### ISSUE TITLE
Report exception to topmost TryCatch or if verbose

### ISSUE THREAD

**Issue by brendandahl** [mozilla/spidernode#89]
Once propagating exceptions is implemented CheckReportExternalException will need extra logic to only report the exception if this is the topmost TryCatch or if verbose reporting is enabled.

**Comment by brendandahl** [comment]
Depends on #51

**Comment by ehsan** [comment]
Hmm, isn't it a dupe of #51?

**Comment by ehsan** [comment]
Oh, nm, I was misreading this somehow! :-)
